# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
inhibit_all_warnings!

target 'CUtilityDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
 use_frameworks!

  # Pods for ZWToolDemo
 pod 'YYUtility', :path => '../'
 
 post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
#              config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
              if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 13.0
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
              end
          end
      end
  end

end
